repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - name: Large files
        always_run: true
        id: check-added-large-files
      - name: Merge conflicts
        always_run: true
        id: check-merge-conflict
      - name: Scripts executable
        always_run: true
        id: check-shebang-scripts-are-executable
      - id: detect-private-key
        always_run: true
      - name: End of file newline
        always_run: true
        id: end-of-file-fixer
      - id: trailing-whitespace
        always_run: true
      - id: no-commit-to-branch
        always_run: true

  # Ansible
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v25.8.1
    hooks:
      - id: ansible-lint
