---
- name: Desktop
  hosts: all
  become: true
  roles:
    - common
    - brave
    - docker
    - proton_vpn
    - user
    - vagrant
    - virtual_box
    - vs_code
    - warp_terminal
    - zoom


# https://signal.org/download/#
