---
- name: GUI
  hosts: all
  become: true
  roles:
    - base_packages
    - brave
    - docker
    # TODO: fix
    # - proton_vpn
    - user
    - vagrant
    - virtual_box
    # TODO: fix
    # - vs_code
    # - zoom
