# https://docs.ollama.com/linux
---
- name: "Install : packages"
  ansible.builtin.apt:
    name: zstd

- name: Install ollama # noqa risky-shell-pipe command-instead-of-module
  ansible.builtin.shell: curl -fsSL https://ollama.com/install.sh | sh
  args:
    creates: /usr/local/bin/ollama
  register: ollama_install

- name: Create ollama data directory
  ansible.builtin.file:
    path: "{{ server.base_dir }}/ollama"
    state: directory
    owner: ollama
    group: ollama
    mode: "0755"

- name: Put ollama service
  ansible.builtin.template:
    src: ollama.service.j2
    dest: /etc/systemd/system/ollama.service
    owner: root
    group: root
    # todo:
    mode: "0644"
  register: ollama_service_unit
  vars:
    base_dir: "{{ server.base_dir }}"

- name: Start ollama service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: ollama
    enabled: true
    state: "{{ 'restarted' if ollama_service_unit.changed else 'started' }}"

- name: Check ollama is available
  ansible.builtin.command: ollama --version
  register: ollama_check
  changed_when: false
