# https://brave.com/linux/
---
- name: "Install : apt key"
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: 644

- name: "Configure : apt source"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present

- name: "Apt : install"
  ansible.builtin.apt:
    update_cache: true
    name: brave-browser
