# https://docs.warp.dev/getting-started/getting-started-with-warp
---
- name: "Add : key"
  ansible.builtin.get_url:
    url: https://releases.warp.dev/linux/keys/warp.asc
    dest: /etc/apt/keyrings/warpdotdev.asc
    mode: 644

- name: "Add : repo"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.asc] https://releases.warp.dev/linux/deb stable main"

- name: "Apt : install"
  ansible.builtin.apt:
    update_cache: true
    name:
      - warp-terminal

# sudo apt-get install wget gpg
# wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
# sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
# sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
# rm warpdotdev.gpg
# sudo apt update && sudo apt install warp-terminal
