# https://docs.docker.com/engine/install/debian/
---
- name: Architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker_arch
  changed_when: docker_arch.changed

- name: "Install : packages"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - python3
    update_cache: true

- name: "Add : apt key"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 644

- name: "Add : repository"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "Install : community edition"
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    update_cache: true
