# https://docs.docker.com/engine/install/debian/
---
- name: Architecture
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: docker_arch

- name: "Install : packages"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl

- name: "Add : repository"
  ansible.builtin.deb822_repository:
    architectures: "{{ docker_arch.stdout }}"
    components: stable
    name: docker
    install_python_debian: true
    signed_by: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    state: present
    suites: "{{ ansible_facts['distribution_release'] }}"
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"

- name: "Install : community edition"
  ansible.builtin.apt:
    update_cache: true
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

- name: "Service : enable and start docker"
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: "Verify : docker is running"
  ansible.builtin.command: docker info
  changed_when: false
