name: ci

on:
  pull_request:
    branches: [main]

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

      # - name: Run ansible-lint
      #   uses: ansible/ansible-lint@main
      #   with:
      #     args: "--force-color"
