name: ci

on:
  pull_request:
    branches: [main]

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "--force-color"
