name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
        playbook:
          - gui
          - server
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible

      - name: Run Ansible Playbook
        run: make local-${{ matrix.playbook }}
