---
- name: "Apt : install"
  # TODO: remove this when GitHub actions updates their Ubuntu runners to 25+
  ignore_errors: true
  register: base_packages_ignore_errors_register
  ansible.builtin.apt:
    name: "{{ apt_install }}"
    update_cache: true
